server {
  listen 80;
  server_tokens off;
  root /usr/share/nginx/html;
  index index.html;

  gzip on;
  gzip_vary on;
  gzip_min_length 256;
  gzip_types text/plain text/css application/javascript application/json text/xml application/xml image/svg+xml;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(woff|ttf)$ {
    add_header Access-Control-Allow-Origin *;
  }

  location ~* \.(js|css|jpg|jpeg|png|svg)$ {
    expires max;
    add_header Cache-Control public;
  }
}
